/** README ******************************************************************************************************************************************
 * This file is responsible for copying the task list generated by each profile to the profile specific overview note, so that the to-do list is     *
 * available anywhere a note is, including in apps that cannot run the panel.                                                                        *
 ***************************************************************************************************************************************************/

/** Imports ****************************************************************************************************************************************/
import { getAllProfiles } from "./database"
import { getFormatter } from "./formats"
import { getNoteContent, setNoteContent } from "./joplin"

/** refreshNoteData *********************************************************************************************************************************
 * Saves the todo list as generated by each profile to the profile specific overview note. The note is only written when its content has actually    *
 * changed, so that unchanged to-do lists do not create a new note revision on every refresh.                                                        *
 ***************************************************************************************************************************************************/
export async function refreshNoteData(){
    for (var profile of await getAllProfiles()){
        if (!profile.noteID) continue
        var formatter = getFormatter(profile, 'markdown')
        var todosMd = await formatter.getTodos()
        var markdownString = `# ${profile.name}\n${todosMd}`
        try {
            var note = await getNoteContent(profile.noteID)
            if (note && note.body === markdownString) continue
            await setNoteContent(profile.noteID, markdownString)
        } catch (error) {
            if (error.message != "Not Found") {
                throw error
            }
        }
    }
}

/** getOverviewNoteIDs ******************************************************************************************************************************
 * Returns the IDs of every note Agenda writes its to-do lists to. Changes to those notes are caused by Agenda itself, so they must not trigger      *
 * another refresh.                                                                                                                                 *
 ***************************************************************************************************************************************************/
export async function getOverviewNoteIDs(){
    var noteIDs = []
    for (var profile of await getAllProfiles()){
        if (profile.noteID) noteIDs.push(profile.noteID)
    }
    return noteIDs
}
